package hospitalms;

import Project.ConnectionProvider;
import java.sql.*;
import java.util.*;
import java.util.jar.Attributes.Name;
import javax.swing.JOptionPane;

/**
 *
 * @author Touseef
 */
public class AddPatients extends javax.swing.JFrame {

    /** Creates new form AddPatients */
    public AddPatients() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Exit = new javax.swing.JButton();
        pID = new javax.swing.JLabel();
        pAge = new javax.swing.JLabel();
        pAddress = new javax.swing.JLabel();
        pName = new javax.swing.JLabel();
        pNumber = new javax.swing.JLabel();
        pGender = new javax.swing.JLabel();
        pMessage = new javax.swing.JLabel();
        pBloodGroup = new javax.swing.JLabel();
        PID = new javax.swing.JTextField();
        PAge = new javax.swing.JTextField();
        PBloodGroup = new javax.swing.JTextField();
        PName = new javax.swing.JTextField();
        PContact = new javax.swing.JTextField();
        PAddress = new javax.swing.JTextField();
        PGender = new javax.swing.JComboBox<>();
        PMessage = new javax.swing.JTextField();
        Save = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(280, 150));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalms/Close.png"))); // NOI18N
        Exit.setText("Close");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 500, 190, 40));

        pID.setBackground(new java.awt.Color(255, 255, 255));
        pID.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        pID.setForeground(new java.awt.Color(255, 255, 255));
        pID.setText("Patient ID :");
        getContentPane().add(pID, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        pAge.setBackground(new java.awt.Color(255, 255, 255));
        pAge.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        pAge.setForeground(new java.awt.Color(255, 255, 255));
        pAge.setText("Age :");
        getContentPane().add(pAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, -1));

        pAddress.setBackground(new java.awt.Color(255, 255, 255));
        pAddress.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        pAddress.setForeground(new java.awt.Color(255, 255, 255));
        pAddress.setText("Address :");
        getContentPane().add(pAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, -1, -1));

        pName.setBackground(new java.awt.Color(255, 255, 255));
        pName.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        pName.setForeground(new java.awt.Color(255, 255, 255));
        pName.setText("Name : ");
        getContentPane().add(pName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        pNumber.setBackground(new java.awt.Color(255, 255, 255));
        pNumber.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        pNumber.setForeground(new java.awt.Color(255, 255, 255));
        pNumber.setText("Contact No. :");
        getContentPane().add(pNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        pGender.setBackground(new java.awt.Color(255, 255, 255));
        pGender.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        pGender.setForeground(new java.awt.Color(255, 255, 255));
        pGender.setText("Gender :");
        getContentPane().add(pGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, -1));

        pMessage.setBackground(new java.awt.Color(255, 255, 255));
        pMessage.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        pMessage.setForeground(new java.awt.Color(255, 255, 255));
        pMessage.setText("Any Major Diseases Suffered Earlier");
        getContentPane().add(pMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, -1));

        pBloodGroup.setBackground(new java.awt.Color(255, 255, 255));
        pBloodGroup.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        pBloodGroup.setForeground(new java.awt.Color(255, 255, 255));
        pBloodGroup.setText("Blood Group :");
        getContentPane().add(pBloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, -1, -1));

        PID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PIDActionPerformed(evt);
            }
        });
        getContentPane().add(PID, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 300, 33));

        PAge.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PAgeActionPerformed(evt);
            }
        });
        getContentPane().add(PAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 300, 33));

        PBloodGroup.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PBloodGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PBloodGroupActionPerformed(evt);
            }
        });
        getContentPane().add(PBloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 300, 33));

        PName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PNameActionPerformed(evt);
            }
        });
        getContentPane().add(PName, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 300, 33));

        PContact.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PContactActionPerformed(evt);
            }
        });
        getContentPane().add(PContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 300, 33));

        PAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PAddressActionPerformed(evt);
            }
        });
        getContentPane().add(PAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 300, 33));

        PGender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));
        getContentPane().add(PGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 300, 39));

        PMessage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PMessageActionPerformed(evt);
            }
        });
        getContentPane().add(PMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 460, 60));

        Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalms/save-icon--1.png"))); // NOI18N
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        getContentPane().add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, 190, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalms/bg1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
            dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void PIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PIDActionPerformed

    private void PAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PAgeActionPerformed

    private void PBloodGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PBloodGroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PBloodGroupActionPerformed

    private void PNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PNameActionPerformed

    private void PContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PContactActionPerformed

    private void PAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PAddressActionPerformed

    private void PMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PMessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PMessageActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
      
        String patientID = PID.getText();
        String Name = PName.getText();
        String ContactNo = PContact.getText();
        String Age = PAge.getText();
        String Gender = (String) PGender.getSelectedItem();
        String bloodGroup = PBloodGroup.getText();
        String address = PAddress.getText();
        String anyMajorDisease = PMessage.getText();

        // Input Validation
        if (patientID.isEmpty() || Name.isEmpty() || ContactNo.isEmpty() || Age.isEmpty() ||
                Gender.isEmpty() || bloodGroup.isEmpty() || address.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all the required fields!");
            return;
        }

        try {
            // Validate Age to be a number
            int ageAsInt = Integer.parseInt(Age);
            if (ageAsInt < 0) {
                JOptionPane.showMessageDialog(this, "Age cannot be negative!");
                return;
            }

            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            st.executeUpdate("insert into patient values ('" + patientID+ "','" + Name + "','" + ContactNo + "'," + Age + ",'" + Gender + "','" + bloodGroup + "','" + address + "','" + anyMajorDisease + "') ");
            JOptionPane.showMessageDialog(null, "Patient Added Successfully!");
            // Clear the form after successful addition
            clearForm();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error Adding Patient: " + e.getMessage());
        }
    }

    private void clearForm() {
        PID.setText("");
        PName.setText("");
        PContact.setText("");
        PAge.setText("");
        PGender.setSelectedIndex(0); // Set combo box to first item (likely 'Male')
        PBloodGroup.setText("");
        PAddress.setText("");
        PMessage.setText("");
    
        
    }//GEN-LAST:event_SaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPatients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPatients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPatients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPatients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPatients().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JTextField PAddress;
    private javax.swing.JTextField PAge;
    private javax.swing.JTextField PBloodGroup;
    private javax.swing.JTextField PContact;
    private javax.swing.JComboBox<String> PGender;
    private javax.swing.JTextField PID;
    private javax.swing.JTextField PMessage;
    private javax.swing.JTextField PName;
    private javax.swing.JButton Save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel pAddress;
    private javax.swing.JLabel pAge;
    private javax.swing.JLabel pBloodGroup;
    private javax.swing.JLabel pGender;
    private javax.swing.JLabel pID;
    private javax.swing.JLabel pMessage;
    private javax.swing.JLabel pName;
    private javax.swing.JLabel pNumber;
    // End of variables declaration//GEN-END:variables

}
