package hospitalms;

import Project.ConnectionProvider;
import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

public class DiagnosisInfo extends javax.swing.JFrame {

    public int flag = 0;

    /**
     * Creates new form DiagnosisInfo
     */
    public DiagnosisInfo() {
        initComponents();
        doesntExist.setVisible(false);
        typeOfWard.setVisible(false);
        choicebar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patientID = new javax.swing.JLabel();
        PID = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        doesntExist = new javax.swing.JLabel();
        symptoms = new javax.swing.JLabel();
        diagnosis = new javax.swing.JLabel();
        medicines = new javax.swing.JLabel();
        symptoms1 = new javax.swing.JTextField();
        diagnosis1 = new javax.swing.JTextField();
        medicines1 = new javax.swing.JTextField();
        Ward = new javax.swing.JLabel();
        typeOfWard = new javax.swing.JLabel();
        checkbox = new javax.swing.JCheckBox();
        choicebar = new javax.swing.JComboBox<>();
        Save = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(280, 150));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        patientID.setFont(new java.awt.Font("Roboto Slab Thin", 1, 14)); // NOI18N
        patientID.setForeground(new java.awt.Color(255, 255, 255));
        patientID.setText("Patient ID :");
        getContentPane().add(patientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        PID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PIDActionPerformed(evt);
            }
        });
        getContentPane().add(PID, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 210, 33));

        Search.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        getContentPane().add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 100, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "patientID", "Name", "ContactNo", "Age", "Gender", "bloodGroup", "address", "anyMajorDisease"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 124, 970, 58));

        doesntExist.setFont(new java.awt.Font("Source Sans Pro Light", 1, 14)); // NOI18N
        doesntExist.setForeground(new java.awt.Color(255, 255, 0));
        doesntExist.setText("PatientID Does not Exist!");
        getContentPane().add(doesntExist, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        symptoms.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        symptoms.setForeground(new java.awt.Color(255, 255, 255));
        symptoms.setText("Symptoms");
        getContentPane().add(symptoms, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        diagnosis.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        diagnosis.setForeground(new java.awt.Color(255, 255, 255));
        diagnosis.setText("Diagnosis");
        getContentPane().add(diagnosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        medicines.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        medicines.setForeground(new java.awt.Color(255, 255, 255));
        medicines.setText("Medicines");
        getContentPane().add(medicines, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, -1));

        symptoms1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                symptoms1ActionPerformed(evt);
            }
        });
        getContentPane().add(symptoms1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 140, 31));
        getContentPane().add(diagnosis1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 140, 31));
        getContentPane().add(medicines1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 140, 31));

        Ward.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Ward.setForeground(new java.awt.Color(255, 255, 255));
        Ward.setText("Ward Required");
        getContentPane().add(Ward, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, -1, -1));

        typeOfWard.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        typeOfWard.setForeground(new java.awt.Color(255, 255, 255));
        typeOfWard.setText("Type Of Ward");
        getContentPane().add(typeOfWard, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, -1, -1));

        checkbox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkbox.setForeground(new java.awt.Color(255, 255, 255));
        checkbox.setText("Yes");
        checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxActionPerformed(evt);
            }
        });
        getContentPane().add(checkbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 240, -1, -1));

        choicebar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        choicebar.setForeground(new java.awt.Color(255, 255, 255));
        choicebar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General", "Single", "Duo" }));
        getContentPane().add(choicebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 290, 113, -1));

        Save.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalms/save-icon--1.png"))); // NOI18N
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        getContentPane().add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, 190, 40));

        Exit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalms/Close.png"))); // NOI18N
        Exit.setText("Close");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 490, 190, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalms/bg1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PIDActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
        String patientID = PID.getText();
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM patient WHERE patientID = '" + patientID + "'");
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            if (!rs.first()) {
                doesntExist.setVisible(true);
            } else {
                doesntExist.setVisible(false);
                flag = 1;
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Database error: " + e.getMessage());
            e.printStackTrace();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
            e.printStackTrace();
        }


    }//GEN-LAST:event_SearchActionPerformed

    private void symptoms1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_symptoms1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_symptoms1ActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed

        if (flag == 1) {
            String patientID = PID.getText();
            String symptoms = symptoms1.getText();
            String diagnosis = diagnosis1.getText();
            String medicines = medicines1.getText();
            String ward;
            String typeOfWard;

            if (checkbox.isSelected()) {
                ward = "Yes";
                typeOfWard = (String) choicebar.getSelectedItem();
            } else {
                ward = "No";
                typeOfWard = "";
            }
            
            try{
                Connection con = ConnectionProvider.getCon();
                Statement st = con.createStatement();
                st.executeUpdate("INSERT INTO patientreport values('"+patientID+"','"+symptoms+"','"+diagnosis+"','"+medicines+"','"+ward+"','"+typeOfWard+"')");
                JOptionPane.showMessageDialog(null, "Successfully Update");
                dispose();
                new DiagnosisInfo().show();
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
                
            }
        }else
            JOptionPane.showMessageDialog(this, "PatientID Does not Exist");
                


    }//GEN-LAST:event_SaveActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        setVisible(false);
    }//GEN-LAST:event_ExitActionPerformed

    private void checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxActionPerformed
        // TODO add your handling code here:

        if (checkbox.isSelected()) {
            typeOfWard.setVisible(true);
            choicebar.setVisible(true);
        } else {
            typeOfWard.setVisible(false);
            choicebar.setVisible(false);
        }
    }//GEN-LAST:event_checkboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiagnosisInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiagnosisInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiagnosisInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiagnosisInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiagnosisInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JTextField PID;
    private javax.swing.JButton Save;
    private javax.swing.JButton Search;
    private javax.swing.JLabel Ward;
    private javax.swing.JCheckBox checkbox;
    private javax.swing.JComboBox<String> choicebar;
    private javax.swing.JLabel diagnosis;
    private javax.swing.JTextField diagnosis1;
    private javax.swing.JLabel doesntExist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel medicines;
    private javax.swing.JTextField medicines1;
    private javax.swing.JLabel patientID;
    private javax.swing.JLabel symptoms;
    private javax.swing.JTextField symptoms1;
    private javax.swing.JLabel typeOfWard;
    // End of variables declaration//GEN-END:variables
}
